### PR TITLE
Backport 1.15.3 to 1.20.1

### PR DESCRIPTION
**Pull request by EthanRStokes**
yes
also frozenlib 1.3.15

### CODE REVIEW

**Comment by EthanRStokes** [comment]
wheres 1.15.2?
did u push those changes lol

**Comment by AViewFromTheTop** [comment]
> wheres 1.15.2?
> did u push those changes lol

Not yet

**Comment by AViewFromTheTop** [comment]
It’s literally just using new FrozenLib that’s the only change

**Comment by AViewFromTheTop** [comment]
are you gonna help out with the last crab issue btw

**Comment by EthanRStokes** [comment]
> are you gonna help out with the last crab issue btw

i will at some point probably
ive been pretty busy lately
on school, wilder wild forge compat, configurable everything 1.0-1.0.2, survival remastered 3.0 beta 1
ykwim
🤯

**Comment by AViewFromTheTop** [comment]
Why tf are you trying to port it to forge lmao

**Comment by EthanRStokes** [comment]
> Why tf are you trying to port it to forge lmao

i meant like
[sinytra connector](https://modrinth.com/mod/connector) compat

**Comment by EthanRStokes** [comment]
updated frozenlib to 1.3.15
might want to change that in 1.20.2

**Comment by EthanRStokes** [comment]
@AViewFromTheTop 
1.14 on modrinth isnt marked for quilt
only fabric

**Comment by EthanRStokes** [comment]
ok updated this to 1.15.3

**Comment by EthanRStokes** [comment]
everything seems to work (according to the results from `/test runall`)

**Comment by NattoRiisa** [comment]
i wish this update released on 1.20.1 cause omg the updates after 1.14 are so good 😭

**Comment by AViewFromTheTop** [comment]
> i wish this update released on 1.20.1 cause omg the updates after 1.14 are so good 😭

Oh shoot I forgot to merge and release this
Bruh moment

**Comment by NattoRiisa** [comment]
> > i wish this update released on 1.20.1 cause omg the updates after 1.14 are so good 😭
> 
> Oh shoot I forgot to merge and release this Bruh moment

lmaooo
i mean take ur time tho i dont bite
i just wanna get the mod but a good portion of the other mods i have installed aren't in 1.20.2 aaaaaaa

**Comment by AViewFromTheTop** [comment]
it is 1.20.1 1.15.3 day my dudes

**Pull request merged**
