### PR TITLE
Vanilla Weathering + Fabric Transfer API + GameTest + Tags + Config + Create Integration

### LINKED ISSUE #13: Ticking Block Entity crash
[crash-2023-02-19_17.13.06-server.txt](https://github.com/AViewFromTheTop/SimpleCopperPipesMC/files/10778174/crash-2023-02-19_17.13.06-server.txt)
[2023-02-19-2.log](https://github.com/AViewFromTheTop/SimpleCopperPipesMC/files/10778179/2023-02-19-2.log)
The pipes are decorative and aren't actually doing anything. There are also hundreds of pipes, and a different one crashes each time. It isn't instant, rather it happens randomly if any pipes are loaded. It could potentially be a mod conflict, but I'm not entirely sure.

### LINKED ISSUE #19: Reverting a pipe's oxidization stage by alt-clicking doesn't fully work on servers
on servers, alt clicking the pipe (or fitting) with an axe does revert the oxidization, but it's missing the particles and the sound
but i noticed that it still does work when another player does it

### LINKED ISSUE #20: Tom's Simple Storage Integration
ok so

tom's simple storage has an inventory connector block
you can extract items out of it with a hopper
but not with a copper pipe

integration would be cool

### LINKED ISSUE #21: copper pipes really broken
copper pipes oriented like this or similar just have stopped working in recent updates
they just dont transfer items
image

### PR DESCRIPTION
**Pull request by EthanRStokes**
I added mixin extras and switched all of the vanilla copper mechanics to actually use the vanilla methods.
Fixes #19
Fixes #20
Fixes #21
Very likely fixes #13 

Added some tags:
copper_pipes
copper_fittings
ignores_copper_pipe_menu

Added integration with Create's wrenches.

Draft right now just in case I want to add more things.

CHANGELOG:
- Once and for all fixed all Pipe and Fitting transport issues, with the help of Fabric API's Transfer API.
     - This also means that Simple Copper Pipes is now compatible with mods like Tom's Simple Storage and Create.
- All Colored and Glowing Pipes and Fittings can now be re-dyed.
- Copper Pipes and Copper Fittings now finally oxidize properly, using Vanilla's system.
- Fittings now split the flow of items evenly among the Pipeline.
- Fixed particles and sounds when reverting oxidization on pipes and fittings.
- Added a config, found at "./config/simple_copper_pipes.json5."
     - Contains toggles for Fittings having an inventory GUI, Pipes dispensing items (shooting,) and Pipes dispensing special effects (like Ink fountains.)
     - This works alongside Cloth Config.
- Changed the mod id to "simple_copper_pipes." The old mod id, "copper_pipe," is still *temporarily* provided alongside the new one via the mod's .json file.
- Added integration with Create's Wrenches.
- Added FrozenLib as a required dependency.
- Internally added structures for use with Mojang's GameTest Framework.

### CODE REVIEW

**Comment by EthanRStokes** [comment]
also suprisingly not experiencing #21 yet
ill do more testing tmr

**Comment by AViewFromTheTop** [comment]
@Treetrain1 that weathering commit is a fucking blessing

**Comment by EthanRStokes** [comment]
Did a bit of testing in the original scenario where I experienced the bug, and it seems like this somehow fixes #21
I don't know how exactly but you know what I'll take it.

**Comment by EthanRStokes** [comment]
Tonight I’ll try to see if I can make it use Fabric’s Transfer API

**Comment by EthanRStokes** [comment]
> Tonight I’ll try to see if I can make it use Fabric’s Transfer API

Should fix #20 and similar issues

**Comment by AViewFromTheTop** [comment]
java.lang.IllegalArgumentException: No value with id -1
	at net.minecraft.core.IdMap.byIdOrThrow(IdMap.java:22) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.2198-v2.jar:?]
	at net.minecraft.world.level.chunk.HashMapPalette.read(HashMapPalette.java:75) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.2198-v2.jar:?]
	at net.minecraft.world.level.chunk.PalettedContainer.read(PalettedContainer.java:171) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.2198-v2.jar:?]
	at net.minecraft.world.level.chunk.LevelChunkSection.read(LevelChunkSection.java:153) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.2198-v2.jar:?]
	at net.minecraft.world.level.chunk.LevelChunk.replaceWithPacketData(LevelChunk.java:416) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.2198-v2.jar:?]
	at net.minecraft.client.multiplayer.ClientChunkCache.replaceWithPacketData(ClientChunkCache.java:118) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.2198-v2.jar:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.updateLevelChunk(ClientPacketListener.java:712) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.2198-v2.jar:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.handleLevelChunkWithLight(ClientPacketListener.java:680) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.2198-v2.jar:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.handle(ClientboundLevelChunkWithLightPacket.java:49) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.2198-v2.jar:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.handle(ClientboundLevelChunkWithLightPacket.java:25) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.2198-v2.jar:?]
	at net.minecraft.network.protocol.PacketUtils.method_11072(PacketUtils.java:26) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.2198-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.2198-v2.jar:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:29) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.2198-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.2198-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:120) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.2198-v2.jar:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1000) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.2198-v2.jar:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:699) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.2198-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:222) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.2198-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]


@Treetrain1 one of your commits is causing huge issues

**Comment by AViewFromTheTop** [comment]
@Treetrain1 bruh the blocks dont get registered anywhere

**Comment by EthanRStokes** [comment]
> @Treetrain1 bruh the blocks dont get registered anywhere

They do

I moved the registration to the actual fields because it needs them to be registered when it loads the class instead of on mod initialization.
It will crash on Quilt Loader because a mixin in the same place is using the registry at that point

**Comment by EthanRStokes** [comment]
Can u revert that “fix screwed up block registering” commit
I’m going to see if i can fix it properly

**Comment by AViewFromTheTop** [comment]
> Can u revert that “fix screwed up block registering” commit I’m going to see if i can fix it properly

ok

**Comment by AViewFromTheTop** [comment]
@Treetrain1 im going to work soon
would you be able to fix Fittings not taking in and pushing out items?
for context, i made fittings control their flow instead of having pipes insert and take from them now, for the sake of being able to split up pipelines evenly

**Comment by AViewFromTheTop** [comment]
@Treetrain1 ok i reverted it

**Comment by AViewFromTheTop** [comment]
> @Treetrain1 im going to work soon would you be able to fix Fittings not taking in and pushing out items? for context, i made fittings control their flow instead of having pipes insert and take from them now, for the sake of being able to split up pipelines evenly

please please please try to find why this is happening ive been trying to almost the last hour

**Comment by EthanRStokes** [comment]
oh i know whats causing the registry thing
because particles arent being registered in time lol

**Comment by EthanRStokes** [comment]
> oh i know whats causing the registry thing because particles arent being registered in time lol

nvm i was wrong?

**Comment by AViewFromTheTop** [comment]
> > @Treetrain1 im going to work soon would you be able to fix Fittings not taking in and pushing out items? for context, i made fittings control their flow instead of having pipes insert and take from them now, for the sake of being able to split up pipelines evenly
> 
> please please please try to find why this is happening ive been trying to almost the last hour

@Treetrain1 pleaseeee this is my priority rn

**Comment by EthanRStokes** [comment]
im expanding this PR to make the mod use Fabric's Transfer API, which is a really compatible solution for... transferring 🤯 
basic copper pipe -> chest functionality exists right now but other things are broken rn

**Comment by AViewFromTheTop** [comment]
> im expanding this PR to make the mod use Fabric's Transfer API, which is a really compatible solution for... transferring 🤯
> basic copper pipe -> chest functionality exists right now but other things are broken rn

Well pipes to chests always worked
The only issue I was having is Fittings not taking in or Distributing items, since I made pipes no longer transfer to them and gave that to fittings instead so they can distribute to multiple pipes

**Comment by AViewFromTheTop** [comment]
But I can’t complain if it’ll actually solve issues with other mods ngl
Even though I don’t use other mods
Btw do you think we should make Stone Chests a WorldlyContainer that never shows any slots @Treetrain1? Might be an easy way to do it without needing the NoInteractionStorage stuff and mixins

**Comment by AViewFromTheTop** [comment]
Anyway thank you for giving me the motivation to actually work on this fucking mod past like a change to a single line of code lmao

**Comment by EthanRStokes** [comment]
ima test it with toms simple storage just to see

**Comment by EthanRStokes** [comment]
gonna have to figure out how to make fittings use the transfer api to transfer fluids and stuff

**Comment by EthanRStokes** [comment]
No way this works now

image

**Comment by EthanRStokes** [comment]
thats a major accomplishment for the night ima head off

**Comment by AViewFromTheTop** [comment]
> gonna have to figure out how to make fittings use the transfer api to transfer fluids and stuff

What
They already transfer water and smoke

**Comment by AViewFromTheTop** [comment]
@Treetrain1 oh my god the transfer api saves so much bullshit that i had to put up with prior
seriously thank you
how the hell do you know how to use this stuff

**Comment by AViewFromTheTop** [comment]
I GOT FITTINGS WORKING YESSSS

**Comment by EthanRStokes** [comment]
> > gonna have to figure out how to make fittings use the transfer api to transfer fluids and stuff
> 
> 
> 
> What
> 
> They already transfer water and smoke

Transfer api has fluid transferring
Probably a better way to transfer liquids
I'll try it at some point, probably not tmr, I'm way too busy tomorrow 💀

**Comment by AViewFromTheTop** [comment]
causes an issue with lithium's hopper mixin

**Comment by AViewFromTheTop** [comment]
might be an accesswidener issue actually lemme check

**Comment by EthanRStokes** [comment]
ok so
`WeatheringCopperMixin` and `HoneyCombItemMixin` are going to cause Quilt's block content registries to not work.
how do we like
add compatiblity with a quilt mod...

**Comment by EthanRStokes** [comment]
> ok so `WeatheringCopperMixin` and `HoneyCombItemMixin` are going to cause Quilt's block content registries to not work. how do we like add compatiblity with a quilt mod...

i mean could just have a quilt branch that just has the quilt block content registry stuff instead of the mixins
then like
upload a separate version

**Comment by AViewFromTheTop** [comment]
> > ok so `WeatheringCopperMixin` and `HoneyCombItemMixin` are going to cause Quilt's block content registries to not work. how do we like add compatiblity with a quilt mod...
> 
> i mean could just have a quilt branch that just has the quilt block content registry stuff instead of the mixins then like upload a separate version

i smell frozenlib

**Comment by EthanRStokes** [comment]
> > > ok so `WeatheringCopperMixin` and `HoneyCombItemMixin` are going to cause Quilt's block content registries to not work. how do we like add compatiblity with a quilt mod...
> 
> > 
> 
> > i mean could just have a quilt branch that just has the quilt block content registry stuff instead of the mixins then like upload a separate version
> 
> 
> 
> i smell frozenlib

Like.. a register method then have platform specific frozenlib? In that case, we would need to not include frozenlib in wilder wild or configurable everything

**Comment by EthanRStokes** [comment]
Pov Treetrain1 after he tries Kotlin for the first time in the MrBeast Mod
image

**Comment by EthanRStokes** [comment]
Would you say the mod would benefit from using the transfer api for fluids and/or smoke?

**Comment by EthanRStokes** [comment]
> @Treetrain1 oh my god the transfer api saves so much bullshit that i had to put up with prior
> seriously thank you
> how the hell do you know how to use this stuff

I learned just very recently
I just like… looked at the fabric api source code
I guess

**Comment by AViewFromTheTop** [comment]
> Pov Treetrain1 after he tries Kotlin for the first time in the MrBeast Mod
> image

God fucking no I literally won’t be able to work on that mod either.
Null pointers are so easy to avoid it’s just a couple lines of code

**Comment by AViewFromTheTop** [comment]
> Would you say the mod would benefit from using the transfer api for fluids and/or smoke?

Well I already made an entire system for that
I’m not too sure because the liquid transport is solely for extra features, NOT for actual transport
I would bother with liquid transport after this PR is merged just so we don’t have to deal with more nonsense during development

**Comment by EthanRStokes** [comment]
> > Would you say the mod would benefit from using the transfer api for fluids and/or smoke?
> 
> Well I already made an entire system for that I’m not too sure because the liquid transport is solely for extra features, NOT for actual transport I would bother with liquid transport after this PR is merged just so we don’t have to deal with more nonsense during development

Ok
In that case, is there anything left before this PR is considered complete?
Any known missing functionality?
Or does it just need more testing?

**Comment by EthanRStokes** [comment]
Maybe we could have some sort of gametest world we could use to test the pipes.
Just to be sure everything works.

**Comment by AViewFromTheTop** [comment]
> Maybe we could have some sort of gametest world we could use to test the pipes.
> Just to be sure everything works.

That’d be awesome
Also I would like for the mod to have a config as well, WW style
That’s the only thing left for this PR imo

**Comment by EthanRStokes** [comment]
no way i figured it out
image

**Comment by EthanRStokes** [comment]
ok so didnt know this before but the /test command runs the gametest stuff

just like
/test runall

**Comment by EthanRStokes** [comment]
#firstgametest!

image

**Comment by EthanRStokes** [comment]
ok thats actually nice
image

**Comment by EthanRStokes** [comment]
man
image

**Comment by AViewFromTheTop** [comment]
> man image

what

**Comment by EthanRStokes** [comment]
before, did copper pipes make a sound when inputting into a chest? or is it just when extracting?

**Comment by EthanRStokes** [comment]
is something like this supposed to have equal output in each chest?
or is it supposed to be random
image

**Comment by AViewFromTheTop** [comment]
> before, did copper pipes make a sound when inputting into a chest? or is it just when extracting?

extracting
i dont think merp ever made an insert sound, nor did i ask her to my knowledge

**Comment by EthanRStokes** [comment]
i finally figured out how to do hotswap again in the new intellij ui

ctrl + shift + f9 then reload 🤯 
lets go i can actually do things fast now

**Comment by EthanRStokes** [comment]
according to the transfer api, this should work, but its not working
image

**Comment by AViewFromTheTop** [comment]
> according to the transfer api, this should work, but its not working
> image

Did you put a block behind the pipe

**Comment by AViewFromTheTop** [comment]
Wait maybe that’s just for dispensing idk

**Comment by EthanRStokes** [comment]
> Wait maybe that’s just for dispensing idk

no, hoppers can put things into composters



also dispense sounds arent playing
when pipes throw items out into the world

**Comment by EthanRStokes** [comment]
fixed the composter bug

what kinds of options would be in the config?

**Comment by AViewFromTheTop** [comment]
> fixed the composter bug


No wayyyy poger 

> what kinds of options would be in the config?

Enabling and disabling pipe sounds, toggle for showing tooltips of pipe and fitting speeds, toggle for letting people normally open fittings like chests, enabling or disabling dispensing and/or special effect dispenses (like glow ink’s particles)

**Comment by EthanRStokes** [comment]
> Enabling and disabling pipe sounds, toggle for showing tooltips of pipe and fitting speeds, toggle for letting people normally open fittings like chests, enabling or disabling dispensing and/or special effect dispenses (like glow ink’s particles)

ok do i use frozenlib for the config
frozenlib optional dependency?

**Comment by AViewFromTheTop** [comment]
> ok do i use frozenlib for the config frozenlib optional dependency?

Up to you but I’d preferably use cloth since FrozenLib gets updated with big changes frequently and nobody wants to download it separately
Plus Quilt can’t dare to handle two copies of the same mod with different versions being present (which is dumb as fuck unlike Fabric) so updating WW and lib would make Copper Pipes crash on there without a new update for pipes

**Comment by EthanRStokes** [comment]
man what is copilot trying to do 💀 
copper pipe stairs
image

**Comment by AViewFromTheTop** [comment]
> man what is copilot trying to do 💀
> copper pipe stairs
> image

Tf is copilot

**Comment by AViewFromTheTop** [comment]
Wait @Treetrain1 what if you sneek peeked that LMAO

**Comment by EthanRStokes** [comment]
> > man what is copilot trying to do 💀
> 
> > copper pipe stairs
> 
> > image
> 
> 
> 
> Tf is copilot

GitHub Copilot

**Comment by EthanRStokes** [comment]
i feel like it would make sense to change the mod id from "copper_pipe" to  "simple_copper_pipes"
because for the config file, copper_pipe.json5 doesnt really make sense
in large modpacks it may cause difficulty finding the file

**Comment by AViewFromTheTop** [comment]
> i feel like it would make sense to change the mod id from "copper_pipe" to "simple_copper_pipes"
> because for the config file, copper_pipe.json5 doesnt really make sense
> in large modpacks it may cause difficulty finding the file

Ok
Will need a FrozenLib update to keep up with that change though

**Comment by EthanRStokes** [comment]
Anyway, if you find any bugs left over after all the changes let me know. I'll see if I can fix them before this PR is merged.

**Comment by EthanRStokes** [comment]
> > i feel like it would make sense to change the mod id from "copper_pipe" to "simple_copper_pipes"
> > because for the config file, copper_pipe.json5 doesnt really make sense
> > in large modpacks it may cause difficulty finding the file
> 
> Ok Will need a FrozenLib update to keep up with that change though

I can make it provide copper pipe still
So it wont break anything

**Comment by EthanRStokes** [comment]
Providing “copper_pipe” should be temporary though

**Comment by EthanRStokes** [comment]
Oh right I need to fix dispense sounds

**Comment by EthanRStokes** [comment]
Wait so what’s preventing the player from opening a menu from copper fittings right now?

**Comment by AViewFromTheTop** [comment]
> Wait so what’s preventing the player from opening a menu from copper fittings right now?

Intentional design choice since it’s not supposed to be regular storage like a chest, I’d prefer for it to be only useable with pipes
But it would be nice to have a config for it

**Comment by EthanRStokes** [comment]
> > Wait so what’s preventing the player from opening a menu from copper fittings right now?
> 
> Intentional design choice since it’s not supposed to be regular storage like a chest, I’d prefer for it to be only useable with pipes But it would be nice to have a config for it

I mean like how are you preventing it?
I’m confused because the AbstractSimpleCopperBlockEntity has the menu thing but I can’t find any other mention of that

**Comment by EthanRStokes** [comment]
> > > Wait so what’s preventing the player from opening a menu from copper fittings right now?
> > 
> > 
> > Intentional design choice since it’s not supposed to be regular storage like a chest, I’d prefer for it to be only useable with pipes But it would be nice to have a config for it
> 
> I mean like how are you preventing it? I’m confused because the AbstractSimpleCopperBlockEntity has the menu thing but I can’t find any other mention of that

Nevermind I’m stupid

**Comment by EthanRStokes** [comment]
When opening fittings, should it award the inspect pipe stat, an inspect fitting stat, or nothing at all?

**Comment by AViewFromTheTop** [comment]
> When opening fittings, should it award the inspect pipe stat, an inspect fitting stat, or nothing at all?

Inspect Fitting

**Comment by EthanRStokes** [comment]
nvm dispense sounds work

**Comment by EthanRStokes** [comment]
right now is there anything that lets copper pipes pick up items off the ground and put them into the pipeline, except for hoppers?

**Comment by AViewFromTheTop** [comment]
> right now is there anything that lets copper pipes pick up items off the ground and put them into the pipeline, except for hoppers?

no

**Comment by EthanRStokes** [comment]
copper pipe 

> > right now is there anything that lets copper pipes pick up items off the ground and put them into the pipeline, except for hoppers?
> 
> no

is that a stupid idea
would something like that fit

like an item sucker or copper funnel or something similar

**Comment by AViewFromTheTop** [comment]
> is that a stupid idea would something like that fit
> 
> like an item sucker or copper funnel or something similar

hoppers make a lot more sense
dont want to make them useless

**Comment by EthanRStokes** [comment]
Oh, should the frozenlib dependency be required, optional, or included?

**Comment by EthanRStokes** [comment]
Is fitting distribution even?

**Comment by AViewFromTheTop** [comment]
> Oh, should the frozenlib dependency be required, optional, or included?

preferably optional but id like it to run without frozenlib

**Comment by EthanRStokes** [comment]
i dont know how to make the dependency optional

**Comment by EthanRStokes** [comment]
> i dont know how to make the dependency optional

even with this semi interaction handler
the comment annotation is gonna error
image

**Comment by AViewFromTheTop** [comment]
@Treetrain1 read my comment on that PR for WW
I think the cloth config stuff should just be its own mod
Would be better that way imo

**Comment by EthanRStokes** [comment]
> @Treetrain1 read my comment on that PR for WW I think the cloth config stuff should just be its own mod Would be better that way imo

frozenlib kotlin?

**Comment by EthanRStokes** [comment]
oh i thought i just finished the pr

no

errors during gametest
image

**Comment by EthanRStokes** [comment]
At this point, I'd consider my changes to be complete.
if you could review this and test it that'd be great.

**Comment by AViewFromTheTop** [comment]
> At this point, I'd consider my changes to be complete.
> if you could review this and test it that'd be great.

Very busy lately

**Comment by EthanRStokes** [comment]
One thing I should mention

The mod is now technically compatible with Tom’s Simple Storage
However, one cannot use copper pipes directly on an inventory connector
Because the inventory connector sees the copper pipe as an inventory
And uh
Connects it
So its very buggy

**Comment by AViewFromTheTop** [comment]
> One thing I should mention
> 
> The mod is now technically compatible with Tom’s Simple Storage However, one cannot use copper pipes directly on an inventory connector Because the inventory connector sees the copper pipe as an inventory And uh Connects it So its very buggy

Idk how inventory connectors work
How does it work with hoppers

**Comment by EthanRStokes** [comment]
> > One thing I should mention
> > The mod is now technically compatible with Tom’s Simple Storage However, one cannot use copper pipes directly on an inventory connector Because the inventory connector sees the copper pipe as an inventory And uh Connects it So its very buggy
> 
> Idk how inventory connectors work How does it work with hoppers

I’m not exactly sure how it works but one thing that does work is having one copper pipe on the connector then have it shoot out items
I assume similar happens with a hopper

**Comment by EthanRStokes** [comment]
wait dont merge i found a critical issue

**Comment by EthanRStokes** [comment]
copper pipes transfer into another copper pipe even if its full, deleting items

**Comment by EthanRStokes** [comment]
> copper pipes transfer into another copper pipe even if its full, deleting items

fixed it!
i just added another check of the amount transferred before committing transfer changes

**Comment by EthanRStokes** [comment]
ok now this is actually ready for merge

**Comment by AViewFromTheTop** [comment]
alright @Treetrain1 can you run me down what was added cause i need to do the changelog

**Comment by AViewFromTheTop** [comment]
do we still need to do the config screen

**Comment by EthanRStokes** [comment]
> do we still need to do the config screen

no i did that already

**Comment by EthanRStokes** [comment]
> alright @Treetrain1 can you run me down what was added cause i need to do the changelog

yeah ill just update the changelog in the topmost message of this PR

**Comment by EthanRStokes** [comment]
ok i think the changelog is mostly done

**Comment by AViewFromTheTop** [comment]
> ok i think the changelog is mostly done

Thank you it’s just gonna be a bit cause I’m going out but probably 10 or 11 I can get it merged

**Comment by EthanRStokes** [comment]
> > ok i think the changelog is mostly done
> 
> 
> 
> Thank you it’s just gonna be a bit cause I’m going out but probably 10 or 11 I can get it merged

🤯

**Comment by AViewFromTheTop** [comment]
> 🤯

sorry tree i was working on music and fell asleep before I could merge

**Comment by AViewFromTheTop** [comment]
merging now thank you @Treetrain1 this is absolutely amazing

**Comment by AViewFromTheTop** [comment]
wait

**Comment by AViewFromTheTop** [comment]
need to update the frozenlib dont i

**Comment by AViewFromTheTop** [comment]
oh you already did that too damnnnn

**Comment by AViewFromTheTop** [comment]
@Treetrain1 how hard is pipes 1.20.2 going to be

**Comment by AViewFromTheTop** [comment]
i see what you did there btw and i made frozenlib included in the build

**Pull request merged**
